# Generated by Django 4.0 on 2024-01-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_latitude', models.DecimalField(decimal_places=16, max_digits=50)),
                ('drop_latitude', models.DecimalField(decimal_places=16, max_digits=50)),
                ('pickup_longitude', models.DecimalField(decimal_places=16, max_digits=50)),
                ('drop_longitude', models.DecimalField(decimal_places=16, max_digits=50)),
                ('drop_address', models.TextField()),
                ('pickup_address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pickuplocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='pickup_location',
        ),
        migrations.DeleteModel(
            name='DropLocation',
        ),
        migrations.DeleteModel(
            name='PickUpLocation',
        ),
        migrations.AddField(
            model_name='pdlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customusers'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pdlocation'),
        ),
    ]
