# Generated by Django 4.0 on 2024-01-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pdlocation_remove_pickuplocation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='people_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
