# Generated by Django 4.0 on 2024-01-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customusers_people_count_customusers_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='is_accepted',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
