# Generated by Django 4.0 on 2024-01-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_loaction_address_customusers_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdlocation',
            name='acpted_driver',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
