# Generated by Django 4.0 on 2024-01-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pdlocation_acpted_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdlocation',
            name='acpted_driver',
            field=models.IntegerField(default=0),
        ),
    ]
