# Generated by Django 4.0 on 2024-01-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_pdlocation_acpted_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdlocation',
            name='current_longitude',
            field=models.DecimalField(decimal_places=16, default=float, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdlocation',
            name='destination_latitude',
            field=models.DecimalField(decimal_places=16, default=float, max_digits=50),
            preserve_default=False,
        ),
    ]
