# Generated by Django 4.0 on 2024-01-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pdlocation_current_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
